In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models
deep = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

wide = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )



# print them out to have a look
print(deep)
print(' ')
print(wide)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)


# Checking Parameters

In [3]:
for param in deep.named_parameters():
    print(param)
    print('-------------')

('0.weight', Parameter containing:
tensor([[-0.0786,  0.6759],
        [-0.4555,  0.3974]], requires_grad=True))
-------------
('0.bias', Parameter containing:
tensor([ 0.6954, -0.0413], requires_grad=True))
-------------
('1.weight', Parameter containing:
tensor([[-0.0024,  0.6080],
        [-0.1968, -0.4783]], requires_grad=True))
-------------
('1.bias', Parameter containing:
tensor([ 0.5409, -0.1632], requires_grad=True))
-------------
('2.weight', Parameter containing:
tensor([[ 0.0192, -0.5720],
        [ 0.3347, -0.2997],
        [-0.0828,  0.3275]], requires_grad=True))
-------------
('2.bias', Parameter containing:
tensor([ 0.3047, -0.3402,  0.2541], requires_grad=True))
-------------


In [4]:
for p in wide.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[-0.3307,  0.0422],
        [ 0.1839,  0.2560],
        [-0.1687,  0.0802],
        [ 0.4770, -0.4043]], requires_grad=True)
 
Parameter containing:
tensor([ 0.2573, -0.5367, -0.5668, -0.6522], requires_grad=True)
 
Parameter containing:
tensor([[-0.1277,  0.0472,  0.2251,  0.4862],
        [-0.2853, -0.4386,  0.4768, -0.4162],
        [ 0.1084, -0.2499, -0.4262, -0.1069]], requires_grad=True)
 
Parameter containing:
tensor([-0.0057,  0.3591,  0.3644], requires_grad=True)
 


In [23]:
# now count the total number of trainable parameters
from torchsummary import summary
summary(wide,input_size=(1,2),batch_size=-1)


----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [24]:
from torchsummary import summary
summary(deep,input_size=(1,2),batch_size=-1)

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 2]               6
            Linear-2                 [-1, 1, 2]               6
            Linear-3                 [-1, 1, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
